<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRSystem.Common\HRSystem.Common.csproj" />
    <ProjectReference Include="..\HRSystem.Data\HRSystem.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sib_api_v3_sdk" Version="4.0.2" />
  </ItemGroup>

</Project>
