// <auto-generated />
using System;
using HRSystem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRSystem.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPasswordChangeRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HRSystem.Data.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInTime = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CheckOutTime = new DateTime(2025, 3, 10, 16, 30, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 10),
                            EmployeeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CheckInTime = new DateTime(2025, 3, 11, 8, 15, 0, 0, DateTimeKind.Utc),
                            CheckOutTime = new DateTime(2025, 3, 11, 16, 45, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 11),
                            EmployeeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CheckInTime = new DateTime(2025, 3, 12, 7, 55, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 12),
                            EmployeeId = 6,
                            IsDeleted = false,
                            Notes = "Forgot checkout — corrected next day."
                        },
                        new
                        {
                            Id = 4,
                            CheckInTime = new DateTime(2025, 3, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            CheckOutTime = new DateTime(2025, 3, 13, 17, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 13),
                            EmployeeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CheckInTime = new DateTime(2025, 3, 14, 8, 30, 0, 0, DateTimeKind.Utc),
                            CheckOutTime = new DateTime(2025, 3, 14, 16, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 14),
                            EmployeeId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CheckInTime = new DateTime(2025, 3, 17, 7, 45, 0, 0, DateTimeKind.Utc),
                            CheckOutTime = new DateTime(2025, 3, 17, 15, 30, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2025, 3, 17),
                            EmployeeId = 1,
                            IsDeleted = false,
                            Notes = "Half day"
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ManagerId = 2,
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ManagerId = 3,
                            Name = "Human Resources"
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "admin@hr.com",
                            FirstName = "System",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = true,
                            LastName = "Administrator",
                            Salary = 95000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "jane@hr.com",
                            FirstName = "Jane",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Smith",
                            Salary = 82000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "bob@hr.com",
                            FirstName = "Bob",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Jones",
                            Salary = 83000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "alice@it.com",
                            FirstName = "Alice",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Brown",
                            Salary = 62000m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "charlie@hr.com",
                            FirstName = "Charlie",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Wilson",
                            Salary = 61000m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "diana@it.com",
                            FirstName = "Diana",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Lee",
                            Salary = 63000m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "evan@hr.com",
                            FirstName = "Evan",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Clark",
                            Salary = 64000m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "fiona@it.com",
                            FirstName = "Fiona",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Hall",
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "george@hr.com",
                            FirstName = "George",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Young",
                            Salary = 66000m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "hannah@it.com",
                            FirstName = "Hannah",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "King",
                            Salary = 67000m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "ian@hr.com",
                            FirstName = "Ian",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Wright",
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "julia@it.com",
                            FirstName = "Julia",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Scott",
                            Salary = 69000m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "kevin@hr.com",
                            FirstName = "Kevin",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Green",
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "laura@it.com",
                            FirstName = "Laura",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Adams",
                            Salary = 71000m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "michael@hr.com",
                            FirstName = "Michael",
                            HireDate = new DateOnly(2024, 6, 1),
                            IsActive = true,
                            IsDeleted = false,
                            IsHR = false,
                            LastName = "Baker",
                            Salary = 72000m
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("AssignedToId");

                    b.ToTable("EmployeeTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedById = 2,
                            AssignedToId = 4,
                            CreatedAt = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update internal wiki for onboarding.",
                            DueDate = new DateOnly(2025, 11, 30),
                            IsDeleted = false,
                            Status = (byte)0,
                            Title = "Review API documentation"
                        },
                        new
                        {
                            Id = 2,
                            AssignedById = 2,
                            AssignedToId = 6,
                            CreatedAt = new DateTime(2025, 2, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Record short walkthrough of dashboard features.",
                            DueDate = new DateOnly(2025, 10, 15),
                            IsDeleted = false,
                            Status = (byte)1,
                            Title = "Prepare sprint demo",
                            UpdatedAt = new DateTime(2025, 2, 15, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignedById = 3,
                            AssignedToId = 5,
                            CompletionNotes = "Updated checklist published at https://intranet/hr/policy-checklist",
                            CreatedAt = new DateTime(2025, 2, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateOnly(2025, 9, 1),
                            IsDeleted = false,
                            Status = (byte)2,
                            Title = "Update HR policy checklist",
                            UpdatedAt = new DateTime(2025, 2, 15, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssignedById = 3,
                            AssignedToId = 7,
                            CreatedAt = new DateTime(2025, 2, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = (byte)0,
                            Title = "Schedule 1:1 meetings"
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("LeaveType")
                        .HasColumnType("tinyint");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "LeaveType")
                        .IsUnique();

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 2,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 3,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 3,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 4,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 4,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 5,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 5,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = 6,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = 6,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 13,
                            EmployeeId = 7,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 14,
                            EmployeeId = 7,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 15,
                            EmployeeId = 8,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 16,
                            EmployeeId = 8,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 17,
                            EmployeeId = 9,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 18,
                            EmployeeId = 9,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 19,
                            EmployeeId = 10,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 20,
                            EmployeeId = 10,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 21,
                            EmployeeId = 11,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 22,
                            EmployeeId = 11,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 23,
                            EmployeeId = 12,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 24,
                            EmployeeId = 12,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 25,
                            EmployeeId = 13,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 26,
                            EmployeeId = 13,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 27,
                            EmployeeId = 14,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 28,
                            EmployeeId = 14,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 29,
                            EmployeeId = 15,
                            LeaveType = (byte)0,
                            TotalDays = 20,
                            UsedDays = 0,
                            Year = 2025
                        },
                        new
                        {
                            Id = 30,
                            EmployeeId = 15,
                            LeaveType = (byte)1,
                            TotalDays = 10,
                            UsedDays = 0,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte>("LeaveType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 4,
                            EndDate = new DateOnly(2025, 8, 8),
                            LeaveType = (byte)0,
                            Reason = "Summer vacation",
                            RequestDate = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2025, 8, 4),
                            Status = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            ApprovedAt = new DateTime(2025, 2, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            ApprovedBy = 1,
                            EmployeeId = 5,
                            EndDate = new DateOnly(2025, 7, 3),
                            LeaveType = (byte)1,
                            RequestDate = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2025, 7, 1),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 6,
                            EndDate = new DateOnly(2025, 9, 12),
                            LeaveType = (byte)2,
                            Reason = "Personal errands",
                            RejectionReason = "Team coverage not available for those dates.",
                            RequestDate = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2025, 9, 10),
                            Status = (byte)2
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 8,
                            EndDate = new DateOnly(2025, 10, 5),
                            LeaveType = (byte)0,
                            Reason = "Conference travel",
                            RequestDate = new DateTime(2025, 2, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateOnly(2025, 10, 1),
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("NetSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalBonus")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalDeduction")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("EmployeeId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Payrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 62000m,
                            CreatedAt = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 4,
                            Month = 4,
                            NetSalary = 62800m,
                            ProcessedBy = 1,
                            Status = (byte)0,
                            TotalBonus = 1000m,
                            TotalDeduction = 200m,
                            Year = 2025
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 61000m,
                            CreatedAt = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 5,
                            Month = 5,
                            NetSalary = 61350m,
                            ProcessedAt = new DateTime(2025, 3, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProcessedBy = 1,
                            Status = (byte)1,
                            TotalBonus = 500m,
                            TotalDeduction = 150m,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("HRSystem.Data.Models.PayrollItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("ItemType")
                        .HasColumnType("tinyint");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PayrollId");

                    b.ToTable("PayrollItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000m,
                            Description = "Q1 performance bonus",
                            ItemType = (byte)0,
                            PayrollId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200m,
                            Description = "Health insurance contribution",
                            ItemType = (byte)1,
                            PayrollId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500m,
                            Description = "Team milestone bonus",
                            ItemType = (byte)0,
                            PayrollId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 150m,
                            Description = "Parking pass",
                            ItemType = (byte)1,
                            PayrollId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRSystem.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.Attendance", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.Department", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.Employee", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.EmployeeTask", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.LeaveBalance", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.LeaveRequest", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.Payroll", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRSystem.Data.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HRSystem.Data.Models.PayrollItem", b =>
                {
                    b.HasOne("HRSystem.Data.Models.Payroll", null)
                        .WithMany()
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HRSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HRSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HRSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
